apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: create-deployment-role-binding
  namespace: jenkins
subjects:
- kind: ServiceAccount
  name: jenkins
  namespace: default
roleRef:
  kind: Role
  name: create-deployment-role
  apiGroup: rbac.authorization.k8s.io